### ISSUE TITLE
version information missing

### ISSUE THREAD

**Issue by CristianCantoro** [elliottslaughter/integrity-checker#4]
The `--version`is not displaying any version number 
```
$ ick --version
Integrity Checker 
$ ick build --version
ick-build 
```

**Comment by elliottslaughter** [comment]
Yes, I see that. It seems to be an issue when installing from crates.io. When you build locally it has the right version:

```
$ ick --version
Integrity Checker 
$ cargo run -- --version
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `target/debug/ick --version`
Integrity Checker 0.1.0
```

My guess is we may be looking at a clap bug here, since all we're doing is calling [clap::clap_version!](https://docs.rs/clap/2.9.3/clap/macro.crate_version!.html). According to the documentation, this version comes out of `Cargo.toml`, and I don't see any reason why that wouldn't get packaged with crates.io (in fact, it wouldn't build without that file).

**Comment by elliottslaughter** [comment]
This seems to have been fixed some time ago upstream in clap. I will try to do a release soonish to capture this, in the meantime you can always install via Git:

```
cargo install --git https://github.com/elliottslaughter/integrity-checker.git
```

**Comment by CristianCantoro** [comment]
@elliottslaughter wrote:
> This seems to have been fixed some time ago upstream in clap. I will try to do a release soonish to capture this, in the meantime you can always install via Git:

I confirm that installing via `git` fixes this issue:
```
$ ick -V
Integrity Checker 0.2.1
```

**Comment by elliottslaughter** [comment]
I pushed this to crates.io so users should get it with `cargo install integrity-checker` now.
